# Generated by Django 5.0.9 on 2026-09-22 09:25

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.core.validators
import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("knowledge", "0001_extensions"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ordinal",
                    models.IntegerField(
                        help_text="Position within the source document."
                    ),
                ),
                (
                    "heading_path",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=256),
                        blank=True,
                        default=list,
                        help_text="Heading breadcrumb, outermost first. Used in citations.",
                        size=None,
                    ),
                ),
                (
                    "content",
                    models.TextField(help_text="Markdown. Tables stay tables."),
                ),
                ("content_chars", models.IntegerField(default=0)),
                ("contains_table", models.BooleanField(default=False)),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(
                        blank=True, dimensions=1024, null=True
                    ),
                ),
                (
                    "embedding_model",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("manual", "Service manual"),
                            ("tsb", "Technical service bulletin"),
                            ("dtc_table", "DTC code table"),
                            ("tech_note", "Technician note"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=128
                    ),
                ),
                ("model_year_start", models.IntegerField(blank=True, null=True)),
                ("model_year_end", models.IntegerField(blank=True, null=True)),
                (
                    "system",
                    models.CharField(
                        choices=[
                            ("engine", "Engine"),
                            ("drivetrain", "Drivetrain"),
                            ("brakes", "Brakes"),
                            ("electrical", "Electrical"),
                            ("hvac", "HVAC"),
                            ("emissions", "Emissions / aftertreatment"),
                            ("fuel", "Fuel"),
                            ("suspension", "Suspension"),
                            ("body", "Body"),
                            ("chassis", "Chassis"),
                            ("transmission", "Transmission"),
                            ("general", "General / multi-system"),
                        ],
                        db_index=True,
                        default="general",
                        max_length=32,
                    ),
                ),
                (
                    "tsb_number",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                (
                    "access_level",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("advisor", "Advisor"),
                            ("technician", "Technician"),
                            ("internal", "Internal"),
                        ],
                        default="advisor",
                        max_length=16,
                    ),
                ),
                (
                    "symptom_keywords",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=64),
                        blank=True,
                        default=list,
                        help_text="Advisor-phrasing symptom terms, e.g. 'shudder', 'cold start'.",
                        size=None,
                    ),
                ),
                (
                    "dtc_codes",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=16),
                        blank=True,
                        default=list,
                        help_text="DTC codes mentioned in this chunk, for code -> narrative lookup.",
                        size=None,
                    ),
                ),
                (
                    "search_vector",
                    models.GeneratedField(
                        db_persist=True,
                        expression=models.Func(
                            models.F("heading_path"),
                            models.F("content"),
                            models.F("dtc_codes"),
                            models.F("symptom_keywords"),
                            models.F("tsb_number"),
                            function="rag_chunk_search_vector",
                            output_field=django.contrib.postgres.search.SearchVectorField(),
                        ),
                        output_field=django.contrib.postgres.search.SearchVectorField(),
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "rag_chunks",
            },
        ),
        migrations.CreateModel(
            name="DTCCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Canonical uppercase code, e.g. 'P0299'.",
                        max_length=16,
                        unique=True,
                    ),
                ),
                ("description", models.CharField(max_length=512)),
                (
                    "likely_causes",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=256),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Informational"),
                            ("low", "Low"),
                            ("moderate", "Moderate"),
                            ("high", "High"),
                            ("critical", "Critical - do not dispatch"),
                        ],
                        db_index=True,
                        default="moderate",
                        max_length=16,
                    ),
                ),
                (
                    "applicable_models",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=128),
                        blank=True,
                        default=list,
                        help_text="Empty list = generic OBD-II code, applies to every model.",
                        size=None,
                    ),
                ),
                ("applicable_year_start", models.IntegerField(blank=True, null=True)),
                ("applicable_year_end", models.IntegerField(blank=True, null=True)),
                (
                    "system",
                    models.CharField(
                        choices=[
                            ("engine", "Engine"),
                            ("drivetrain", "Drivetrain"),
                            ("brakes", "Brakes"),
                            ("electrical", "Electrical"),
                            ("hvac", "HVAC"),
                            ("emissions", "Emissions / aftertreatment"),
                            ("fuel", "Fuel"),
                            ("suspension", "Suspension"),
                            ("body", "Body"),
                            ("chassis", "Chassis"),
                            ("transmission", "Transmission"),
                            ("general", "General / multi-system"),
                        ],
                        db_index=True,
                        default="general",
                        max_length=32,
                    ),
                ),
                (
                    "is_generic",
                    models.BooleanField(
                        default=True, help_text="Generic OBD-II code vs. OEM-specific."
                    ),
                ),
                (
                    "advisor_guidance",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Plain-language line an advisor can say to a customer.",
                    ),
                ),
                (
                    "description_embedding",
                    pgvector.django.vector.VectorField(
                        blank=True, dimensions=1024, null=True
                    ),
                ),
                (
                    "embedding_model",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "rag_dtc_codes",
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=512)),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("manual", "Service manual"),
                            ("tsb", "Technical service bulletin"),
                            ("dtc_table", "DTC code table"),
                            ("tech_note", "Technician note"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                (
                    "source_file",
                    models.CharField(
                        help_text="Path or object key of the file this was ingested from.",
                        max_length=1024,
                    ),
                ),
                (
                    "source_uri",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="Canonical OEM location, surfaced in citations when present.",
                        max_length=1024,
                    ),
                ),
                (
                    "oem",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Normalized vehicle model, e.g. 'transit'. Blank = applies to all.",
                        max_length=128,
                    ),
                ),
                (
                    "model_year_start",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1980),
                            django.core.validators.MaxValueValidator(2100),
                        ],
                    ),
                ),
                (
                    "model_year_end",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1980),
                            django.core.validators.MaxValueValidator(2100),
                        ],
                    ),
                ),
                (
                    "system",
                    models.CharField(
                        choices=[
                            ("engine", "Engine"),
                            ("drivetrain", "Drivetrain"),
                            ("brakes", "Brakes"),
                            ("electrical", "Electrical"),
                            ("hvac", "HVAC"),
                            ("emissions", "Emissions / aftertreatment"),
                            ("fuel", "Fuel"),
                            ("suspension", "Suspension"),
                            ("body", "Body"),
                            ("chassis", "Chassis"),
                            ("transmission", "Transmission"),
                            ("general", "General / multi-system"),
                        ],
                        db_index=True,
                        default="general",
                        max_length=32,
                    ),
                ),
                (
                    "tsb_number",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                ("revision", models.CharField(blank=True, default="", max_length=32)),
                ("issued_on", models.DateField(blank=True, null=True)),
                (
                    "access_level",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("advisor", "Advisor"),
                            ("technician", "Technician"),
                            ("internal", "Internal"),
                        ],
                        default="advisor",
                        max_length=16,
                    ),
                ),
                (
                    "is_synthetic",
                    models.BooleanField(
                        default=False,
                        help_text="True for representative sample corpora, so eval numbers measured on them are never mistaken for production numbers.",
                    ),
                ),
                (
                    "content_hash",
                    models.CharField(
                        db_index=True,
                        help_text="SHA-256 of the raw source bytes. Drives idempotent re-ingest.",
                        max_length=64,
                    ),
                ),
                ("ingested_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "rag_documents",
                "indexes": [
                    models.Index(
                        fields=["model", "doc_type"], name="ix_doc_model_type"
                    ),
                    models.Index(
                        fields=["model", "system"], name="ix_doc_model_system"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="document",
            constraint=models.UniqueConstraint(
                fields=("source_file", "content_hash"), name="uniq_doc_source_hash"
            ),
        ),
        migrations.AddConstraint(
            model_name="document",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("model_year_end__isnull", True),
                    ("model_year_start__isnull", True),
                    ("model_year_end__gte", models.F("model_year_start")),
                    _connector="OR",
                ),
                name="ck_doc_year_range",
            ),
        ),
        migrations.AddField(
            model_name="chunk",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chunks",
                to="knowledge.document",
            ),
        ),
        migrations.AddField(
            model_name="dtccode",
            name="source_document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dtc_codes",
                to="knowledge.document",
            ),
        ),
        migrations.AddIndex(
            model_name="chunk",
            index=models.Index(
                fields=["model", "doc_type", "system"], name="ix_chunk_prefilter"
            ),
        ),
        migrations.AddIndex(
            model_name="chunk",
            index=models.Index(
                fields=["model", "model_year_start", "model_year_end"],
                name="ix_chunk_model_years",
            ),
        ),
        migrations.AddIndex(
            model_name="chunk",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["dtc_codes"], name="ix_chunk_dtc_codes"
            ),
        ),
        migrations.AddIndex(
            model_name="chunk",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["symptom_keywords"], name="ix_chunk_symptoms"
            ),
        ),
        migrations.AddConstraint(
            model_name="chunk",
            constraint=models.UniqueConstraint(
                fields=("document", "ordinal"), name="uniq_chunk_doc_ordinal"
            ),
        ),
        migrations.AddIndex(
            model_name="dtccode",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["applicable_models"], name="ix_dtc_models"
            ),
        ),
        migrations.AddIndex(
            model_name="dtccode",
            index=models.Index(
                fields=["system", "severity"], name="ix_dtc_system_severity"
            ),
        ),
    ]
